version: '3'
services:
  fluentd:
    build: fluentd/
    ports:
      - "2055:2055/udp"
    networks:
      intra:
        ipv4_address: 172.16.200.101
    volumes:
      - ./fluentd/netflow-log:/fluentd/netflow-log
    # restart: always
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    expose:
      - 9200:9200
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      intra:
        ipv4_address: 172.16.200.102
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    # restart: always
  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.2
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
      intra:
        ipv4_address: 172.16.200.103
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    # restart: always
      
networks:
  intra:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 172.16.200.0/24
# docker run -it -p 2055:2055 -p 2055:2055/udp --net=host -v $(pwd)/netflow-log:/fluentd/netflow-log logger
